# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nTdnA_IikSP_T3QuA79AzyizEyrQbhDb

Extracting Frames from video
"""

def FrameCapture(path): 
    os.mkdir("Frames")
    vidObj = cv2.VideoCapture(path) 

    q = 0
  
    success = 1
  
    while success: 
  
        success, image = vidObj.read() 
  
        try:
          cv2.imwrite("Frames/frame"+str(q)+".jpg", image) 
        except:
          pass
  
        q=q+1
FrameCapture("/content/1615363610851.mp4")
